version: 2.1

orbs:
  allure: ayte/allure@0.1.3
  browser-tools: circleci/browser-tools@1.4.0
  webex-orb: cxepi/webex-orb@0.4.2

jobs:
  run_tests:
    circleci_ip_ranges: true
    docker:
      - image: cimg/node:16.16.0-browsers
        environment:
          TERM: xterm
    parameters:
      specPath:
        type: string
      trackName:
        type: string
    working_directory: ~/repo
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - allure/install
      - restore_cache:
          name: Restore `package.json` cache
          keys:
            - deps-{{ .Branch }}-{{ checksum "package.json" }}
            - deps-{{ .Branch }}
            - deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          name: Save Cache - NPM and Cypress!
          key: deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run Cypress Tests
          command: npm run cy:run
      - store_test_results:
          name: Store Test Results
          path: results/junit
      - run:
          name: Generate Allure Report
          when: always
          command: npm run allure-report
      - store_artifacts:
          name: Store Allure Report
          path: results/allure-report
      - webex-orb/notify:
          message: >-
            Hi Team, Below is the Cypress API Automation Report in Test Environment for << parameters.trackName >> track. Circle CI Build URL - ${CIRCLE_BUILD_URL} Allure Report - https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/0/results/allure-report/index.html

workflows:
  run_tests_all_tracks:
    jobs:
      - run_tests:
          name: CPMirror
          specPath: "cypress/e2e/**/*.cy.js"  
          trackName: "CPMirror"
          filters:
            branches:
              only:
                - main


#version: 2.1
#orbs:
#  circleci-cli: circleci/circleci-cli@0.1.9
#jobs:
#  build:
#    docker:
#      - image: cypress/browsers:node18.6.0-chrome105-ff104
#    working_directory: ~/repo
#    steps:
#      - checkout
#      # Download and cache dependencies
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "package.json" }}
#            # fallback to using the latest cache if no exact match is found
#            - v1-dependencies-
#
#      - run: npm ci
#      - run: npm run cy:run
#      - run: npm run allure-report