version: 2.1
orbs:
  circleci-cli: circleci/circleci-cli@0.1.9
  allure: ayte/allure@0.1.3
jobs:
  build:
    docker:
      - image: cypress/browsers:node18.6.0-chrome105-ff104
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci
      - run: npm run test

      - run:
          name: Generate Allure Report
          when: always
          command: npm run report:generate
      - store_artifacts:
                name: Store Allure Report
                path: results/allure-report