name: CI

# Controls when the workflow will run
on: push
   
jobs:
  automated-test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
    - name: Install Cypress
      run: npm install cypress --save-dev
       
    - name: Install allure
      run: npm install -g allure-commandline --save-dev
      
    - name: Cypress run
      run: npm run test

    - name: Reports Generate
      run: npm run allure-report
       
    - uses: actions/upload-artifact@master
      with:
        name: allure-results
        path: allure-results
        retention-days: 20
  
    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true
#env:
          # PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # PUBLISH_BRANCH: gh-pages
          # PUBLISH_DIR: allure-history
